name: Cleanup Preview Deployments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Delete Firebase Preview Channel
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: pr-${{ github.event.number }}
        projectId: pokerize-app
        expires: 0
